import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { Buttons, CalculatorCard, FormulaCard, NumericInput, ResultCard, Screen, SectionHeader, styles } from '../src/components';
import { decimalToFraction, mmToInches, mmToThousandths, roundForDisplay, thousandthsToMm } from '../src/domain/math';
import { saveHistory } from '../src/storage/preferences';
import { useTheme } from '../src/theme/ThemeContext';
import { parseLocalizedNumber } from '../src/utils/input';
type Mode='mm'|'thou'|'fraction';
export default function Converter(){const{colors}=useTheme();const[mode,setMode]=useState<Mode>('mm'),[value,setValue]=useState(''),[result,setResult]=useState(''),[detail,setDetail]=useState(''),[error,setError]=useState('');const calc=()=>{try{const n=parseLocalizedNumber(value);if(n===null)throw new Error('Completa los datos para calcular.');let out='',extra='';if(mode==='mm'){out=`${roundForDisplay(mmToThousandths(n))} milésimas`;extra=`${mmToInches(n).toFixed(4)} pulgadas`;}else if(mode==='thou'){out=`${roundForDisplay(thousandthsToMm(n))} mm`;extra=`${(n/1000).toFixed(4)} pulgadas`;}else{const f=decimalToFraction(n);out=`${f.whole?`${f.whole} `:''}${f.numerator?`${f.numerator}/${f.denominator}`:''}\"`;extra=`Error: ${Math.abs(f.error).toFixed(6)}\"`;}setResult(out);setDetail(extra);setError('');void saveHistory({type:'Conversor',summary:value,result:out});}catch(e){setError(e instanceof Error?e.message:'Dato inválido');setResult('')}};return <Screen><ScrollView><SectionHeader title="Conversor" subtitle="Milímetros, pulgadas, milésimas y fracciones."/><View style={styles.row}>{([['mm','mm → pulg.'],['thou','milésimas → mm'],['fraction','decimal → fracción']] as [Mode,string][]).map(([key,label])=><Pressable key={key} onPress={()=>{setMode(key);setResult('')}} style={{flex:1,padding:10,borderRadius:8,backgroundColor:mode===key?colors.primary:colors.surface}}><Text style={{color:mode===key?'white':colors.text,textAlign:'center',fontSize:12}}>{label}</Text></Pressable>)}</View><CalculatorCard><NumericInput label={mode==='mm'?'Milímetros':mode==='thou'?'Milésimas de pulgada':'Pulgadas decimales'} value={value} onChangeText={setValue}/>{error&&<Text style={styles.error}>{error}</Text>}<Buttons onCalculate={calc} onClear={()=>{setValue('');setResult('');setError('')}}/><FormulaCard formula={mode==='mm'?'pulgadas = mm / 25.4':mode==='thou'?'mm = milésimas × 0.0254':'fracción = aproximación al 1/128'}/></CalculatorCard>{result&&<ResultCard label="Resultado" value={result} details={<Text style={styles.resultDetails}>{detail}</Text>}/>}</ScrollView></Screen>}
