import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { AppCard, Screen, SectionHeader } from '../src/components';
import { getFavorites, toggleFavorite } from '../src/storage/preferences';
import { useTheme } from '../src/theme/ThemeContext';
const cards=[{key:'circles',title:'Círculos y módulos',description:'Cálculos de engranajes, módulos y divisiones.',icon:'settings-outline' as const,path:'/circles-modules' as const},{key:'cone',title:'Grados de cono',description:'Calcula inclinaciones y ángulos de conos.',icon:'triangle-outline' as const,path:'/cone-angle' as const},{key:'chord',title:'Longitud de cuerda',description:'Distribución y distancia entre perforaciones.',icon:'ellipse-outline' as const,path:'/chord-length' as const},{key:'converter',title:'Conversor',description:'Milímetros, pulgadas, milésimas y fracciones.',icon:'swap-horizontal-outline' as const,path:'/converter' as const}];
export default function Home(){const{colors,darkMode,toggleTheme}=useTheme();const[favorites,setFavorites]=useState<string[]>([]);useFocusEffect(useCallback(()=>{void getFavorites().then(setFavorites)},[]));const render=(c:typeof cards[number])=><AppCard key={c.key} title={c.title} description={c.description} icon={c.icon} favorite={favorites.includes(c.key)} onPress={()=>router.push(c.path)} onFavorite={()=>void toggleFavorite(c.key).then(setFavorites)}/>;return <Screen><ScrollView showsVerticalScrollIndicator={false}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingTop:24}}><SectionHeader title="MaoMec" subtitle="Cálculos de taller"/><View style={{flexDirection:'row',gap:18}}><Pressable accessibilityLabel="Historial" onPress={()=>router.push('/history')}><Ionicons name="time-outline" size={26} color={colors.text}/></Pressable><Pressable accessibilityLabel="Cambiar tema" onPress={toggleTheme}><Ionicons name={darkMode?'sunny-outline':'moon-outline'} size={26} color={colors.text}/></Pressable></View></View>{favorites.length>0&&<><Text style={{color:colors.text,fontSize:18,fontWeight:'700',marginBottom:10}}>Favoritos</Text>{cards.filter(c=>favorites.includes(c.key)).map(render)}<Text style={{color:colors.text,fontSize:18,fontWeight:'700',marginVertical:10}}>Herramientas</Text></>}{cards.map(render)}</ScrollView></Screen>}
